packages:
  # all packages in subdirs of packages/ and components/
  # - 'packages/**'
  - 'core'
  # - 'svelte'
  - 'ui'
  # - 'grid'
  - 'demos/kitchen-sink'
  - 'demos/demo'
  # - 'framework7/core'
  # - 'framework7/svelte'
  # exclude packages that are inside test directories
  # - '!**/test/**'
