packages:
  # all packages in subdirs of packages/ and components/
  # - 'packages/**'
  - 'core'
  - 'svelte'
  - 'ui'
  - 'jqGrid'
  - 'ag'
  - 'ag-demo'
  - 'demo'
  # exclude packages that are inside test directories
  # - '!**/test/**'
