/* sheet.svelte generated by Svelte v3.38.2 */
import {
	SvelteComponent,
	append,
	assign,
	attr,
	binding_callbacks,
	compute_rest_props,
	create_slot,
	detach,
	element,
	exclude_internal_props,
	get_spread_update,
	init,
	insert,
	safe_not_equal,
	set_attributes,
	space,
	transition_in,
	transition_out,
	update_slot
} from "svelte/internal";

import { createEventDispatcher, onMount, onDestroy } from "svelte";
import { colorClasses } from "../shared/mixins";
import { classNames, createEmitter } from "../shared/utils";
import { restProps } from "../shared/rest-props";
import { app, f7ready } from "../shared/f7";
import { modalStateClasses } from "../shared/modal-state-classes";
const get_static_slot_changes = dirty => ({ sheet: dirty[0] & /*f7Sheet*/ 4 });
const get_static_slot_context = ctx => ({ sheet: /*f7Sheet*/ ctx[2] });
const get_default_slot_changes = dirty => ({ sheet: dirty[0] & /*f7Sheet*/ 4 });
const get_default_slot_context = ctx => ({ sheet: /*f7Sheet*/ ctx[2] });
const get_fixed_slot_changes = dirty => ({ sheet: dirty[0] & /*f7Sheet*/ 4 });
const get_fixed_slot_context = ctx => ({ sheet: /*f7Sheet*/ ctx[2] });

function create_fragment(ctx) {
	let div1;
	let t0;
	let div0;
	let t1;
	let current;
	const fixed_slot_template = /*#slots*/ ctx[24].fixed;
	const fixed_slot = create_slot(fixed_slot_template, ctx, /*$$scope*/ ctx[23], get_fixed_slot_context);
	const default_slot_template = /*#slots*/ ctx[24].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[23], get_default_slot_context);
	const static_slot_template = /*#slots*/ ctx[24].static;
	const static_slot = create_slot(static_slot_template, ctx, /*$$scope*/ ctx[23], get_static_slot_context);
	let div1_levels = [{ class: /*classes*/ ctx[3] }, restProps(/*$$restProps*/ ctx[4])];
	let div1_data = {};

	for (let i = 0; i < div1_levels.length; i += 1) {
		div1_data = assign(div1_data, div1_levels[i]);
	}

	return {
		c() {
			div1 = element("div");
			if (fixed_slot) fixed_slot.c();
			t0 = space();
			div0 = element("div");
			if (default_slot) default_slot.c();
			t1 = space();
			if (static_slot) static_slot.c();
			attr(div0, "class", "sheet-modal-inner");
			set_attributes(div1, div1_data);
		},
		m(target, anchor) {
			insert(target, div1, anchor);

			if (fixed_slot) {
				fixed_slot.m(div1, null);
			}

			append(div1, t0);
			append(div1, div0);

			if (default_slot) {
				default_slot.m(div0, null);
			}

			append(div0, t1);

			if (static_slot) {
				static_slot.m(div0, null);
			}

			/*div0_binding*/ ctx[25](div0);
			/*div1_binding*/ ctx[26](div1);
			current = true;
		},
		p(ctx, dirty) {
			if (fixed_slot) {
				if (fixed_slot.p && (!current || dirty[0] & /*$$scope, f7Sheet*/ 8388612)) {
					update_slot(fixed_slot, fixed_slot_template, ctx, /*$$scope*/ ctx[23], dirty, get_fixed_slot_changes, get_fixed_slot_context);
				}
			}

			if (default_slot) {
				if (default_slot.p && (!current || dirty[0] & /*$$scope, f7Sheet*/ 8388612)) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[23], dirty, get_default_slot_changes, get_default_slot_context);
				}
			}

			if (static_slot) {
				if (static_slot.p && (!current || dirty[0] & /*$$scope, f7Sheet*/ 8388612)) {
					update_slot(static_slot, static_slot_template, ctx, /*$$scope*/ ctx[23], dirty, get_static_slot_changes, get_static_slot_context);
				}
			}

			set_attributes(div1, div1_data = get_spread_update(div1_levels, [
				(!current || dirty[0] & /*classes*/ 8) && { class: /*classes*/ ctx[3] },
				dirty[0] & /*$$restProps*/ 16 && restProps(/*$$restProps*/ ctx[4])
			]));
		},
		i(local) {
			if (current) return;
			transition_in(fixed_slot, local);
			transition_in(default_slot, local);
			transition_in(static_slot, local);
			current = true;
		},
		o(local) {
			transition_out(fixed_slot, local);
			transition_out(default_slot, local);
			transition_out(static_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(div1);
			if (fixed_slot) fixed_slot.d(detaching);
			if (default_slot) default_slot.d(detaching);
			if (static_slot) static_slot.d(detaching);
			/*div0_binding*/ ctx[25](null);
			/*div1_binding*/ ctx[26](null);
		}
	};
}

function instance_1($$self, $$props, $$invalidate) {
	let positionComputed;
	let classes;

	const omit_props_names = [
		"class","opened","animate","top","bottom","position","backdrop","backdropEl","closeByBackdropClick","closeByOutsideClick","closeOnEscape","push","swipeToClose","swipeToStep","swipeHandler","containerEl","instance"
	];

	let $$restProps = compute_rest_props($$props, omit_props_names);
	let { $$slots: slots = {}, $$scope } = $$props;
	const emit = createEmitter(createEventDispatcher, $$props);
	let { class: className = undefined } = $$props;
	let { opened = undefined } = $$props;
	let { animate = undefined } = $$props;
	let { top = undefined } = $$props;
	let { bottom = undefined } = $$props;
	let { position = undefined } = $$props;
	let { backdrop = undefined } = $$props;
	let { backdropEl = undefined } = $$props;
	let { closeByBackdropClick = undefined } = $$props;
	let { closeByOutsideClick = undefined } = $$props;
	let { closeOnEscape = undefined } = $$props;
	let { push = undefined } = $$props;
	let { swipeToClose = undefined } = $$props;
	let { swipeToStep = undefined } = $$props;
	let { swipeHandler = undefined } = $$props;
	let { containerEl = undefined } = $$props;
	let el;
	let innerEl;
	let f7Sheet;
	const state = { isOpened: opened, isClosing: false };

	function instance() {
		return f7Sheet;
	}

	function onOpen(instance) {
		Object.assign(state, { isOpened: true, isClosing: false });
		emit("sheetOpen", [instance]);
		$$invalidate(5, opened = true);
	}

	function onOpened(instance) {
		emit("sheetOpened", [instance]);
	}

	function onClose(instance) {
		Object.assign(state, { isOpened: false, isClosing: true });
		emit("sheetClose", [instance]);
	}

	function onClosed(instance) {
		Object.assign(state, { isClosing: false });
		emit("sheetClosed", [instance]);
		$$invalidate(5, opened = false);
	}

	function onStepProgress(instance, progress) {
		emit("sheetStepProgress", [instance, progress]);
	}

	function onStepOpen(instance) {
		emit("sheetStepOpen", [instance]);
	}

	function onStepClose(instance) {
		emit("sheetStepClose", [instance]);
	}

	let initialWatched = false;

	function watchOpened(openedPassed) {
		if (!initialWatched) {
			initialWatched = true;
			return;
		}

		if (!f7Sheet) return;
		if (openedPassed) f7Sheet.open(); else f7Sheet.close();
	}

	onMount(() => {
		const params = {
			el,
			on: {
				open: onOpen,
				opened: onOpened,
				close: onClose,
				closed: onClosed,
				stepOpen: onStepOpen,
				stepClose: onStepClose,
				stepProgress: onStepProgress
			}
		};

		if (typeof backdrop !== "undefined") params.backdrop = backdrop;
		if (typeof animate !== "undefined") params.animate = animate;
		if (typeof backdropEl !== "undefined") params.backdropEl = backdropEl;
		if (typeof closeByBackdropClick !== "undefined") params.closeByBackdropClick = closeByBackdropClick;
		if (typeof closeByOutsideClick !== "undefined") params.closeByOutsideClick = closeByOutsideClick;
		if (typeof closeOnEscape !== "undefined") params.closeOnEscape = closeOnEscape;
		if (typeof swipeToClose !== "undefined") params.swipeToClose = swipeToClose;
		if (typeof swipeToStep !== "undefined") params.swipeToStep = swipeToStep;
		if (typeof swipeHandler !== "undefined") params.swipeHandler = swipeHandler;
		if (typeof containerEl !== "undefined") params.containerEl = containerEl;

		f7ready(() => {
			if (el && innerEl) {
				const dom7 = app.f7.$;
				const fixedEls = dom7(innerEl).children(".navbar, .toolbar, .tabbar, .searchbar");

				if (fixedEls.length) {
					dom7(el).prepend(fixedEls);
				}
			}

			$$invalidate(2, f7Sheet = app.f7.sheet.create(params));

			if (opened) {
				f7Sheet.open(false);
			}
		});
	});

	onDestroy(() => {
		if (f7Sheet) f7Sheet.destroy();
		$$invalidate(2, f7Sheet = null);
	});

	function div0_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			innerEl = $$value;
			$$invalidate(1, innerEl);
		});
	}

	function div1_binding($$value) {
		binding_callbacks[$$value ? "unshift" : "push"](() => {
			el = $$value;
			$$invalidate(0, el);
		});
	}

	$$self.$$set = $$new_props => {
		$$invalidate(38, $$props = assign(assign({}, $$props), exclude_internal_props($$new_props)));
		$$invalidate(4, $$restProps = compute_rest_props($$props, omit_props_names));
		if ("class" in $$new_props) $$invalidate(6, className = $$new_props.class);
		if ("opened" in $$new_props) $$invalidate(5, opened = $$new_props.opened);
		if ("animate" in $$new_props) $$invalidate(7, animate = $$new_props.animate);
		if ("top" in $$new_props) $$invalidate(8, top = $$new_props.top);
		if ("bottom" in $$new_props) $$invalidate(9, bottom = $$new_props.bottom);
		if ("position" in $$new_props) $$invalidate(10, position = $$new_props.position);
		if ("backdrop" in $$new_props) $$invalidate(11, backdrop = $$new_props.backdrop);
		if ("backdropEl" in $$new_props) $$invalidate(12, backdropEl = $$new_props.backdropEl);
		if ("closeByBackdropClick" in $$new_props) $$invalidate(13, closeByBackdropClick = $$new_props.closeByBackdropClick);
		if ("closeByOutsideClick" in $$new_props) $$invalidate(14, closeByOutsideClick = $$new_props.closeByOutsideClick);
		if ("closeOnEscape" in $$new_props) $$invalidate(15, closeOnEscape = $$new_props.closeOnEscape);
		if ("push" in $$new_props) $$invalidate(16, push = $$new_props.push);
		if ("swipeToClose" in $$new_props) $$invalidate(17, swipeToClose = $$new_props.swipeToClose);
		if ("swipeToStep" in $$new_props) $$invalidate(18, swipeToStep = $$new_props.swipeToStep);
		if ("swipeHandler" in $$new_props) $$invalidate(19, swipeHandler = $$new_props.swipeHandler);
		if ("containerEl" in $$new_props) $$invalidate(20, containerEl = $$new_props.containerEl);
		if ("$$scope" in $$new_props) $$invalidate(23, $$scope = $$new_props.$$scope);
	};

	$$self.$$.update = () => {
		if ($$self.$$.dirty[0] & /*position, top, bottom*/ 1792) {
			$: $$invalidate(22, positionComputed = (() => {
				if (position) return position;
				if (top) return "top";
				if (bottom) return "bottom";
				return "bottom";
			})());
		}

		$: $$invalidate(3, classes = classNames(className, "sheet-modal", `sheet-modal-${positionComputed}`, { "sheet-modal-push": push }, modalStateClasses(state), colorClasses($$props)));

		if ($$self.$$.dirty[0] & /*opened*/ 32) {
			$: watchOpened(opened);
		}
	};

	$$props = exclude_internal_props($$props);

	return [
		el,
		innerEl,
		f7Sheet,
		classes,
		$$restProps,
		opened,
		className,
		animate,
		top,
		bottom,
		position,
		backdrop,
		backdropEl,
		closeByBackdropClick,
		closeByOutsideClick,
		closeOnEscape,
		push,
		swipeToClose,
		swipeToStep,
		swipeHandler,
		containerEl,
		instance,
		positionComputed,
		$$scope,
		slots,
		div0_binding,
		div1_binding
	];
}

class Sheet extends SvelteComponent {
	constructor(options) {
		super();

		init(
			this,
			options,
			instance_1,
			create_fragment,
			safe_not_equal,
			{
				class: 6,
				opened: 5,
				animate: 7,
				top: 8,
				bottom: 9,
				position: 10,
				backdrop: 11,
				backdropEl: 12,
				closeByBackdropClick: 13,
				closeByOutsideClick: 14,
				closeOnEscape: 15,
				push: 16,
				swipeToClose: 17,
				swipeToStep: 18,
				swipeHandler: 19,
				containerEl: 20,
				instance: 21
			},
			[-1, -1]
		);
	}

	get instance() {
		return this.$$.ctx[21];
	}
}

export default Sheet;